language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - python setup.py -q install

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - estetus@gmail.com
    on_success: change
    on_failure: always
